lesson: SpringBoot

enterprise:
  name: My Enterprise
  address:
    street: 123 Main St
    city: Springfield
    state: IL
    zipCode: 62701
  subject:
    - Java
    - C++
    - Python

# 设置启动环境
spring:
  profiles:
    active: dev
---
#配置启动环境
server:
  port: 8080
spring:
  config:
    activate:
      on-profile: dev

---
server:
  port: 81
spring:
  config:
    activate:
      on-profile: uat
---
server:
  port: 82
spring:
  config:
    activate:
      on-profile: prod

